import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';

const roboto = Roboto({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={roboto.className}>
                <ThemeProvider attribute='class' defaultTheme='dark'>
                    {children}
                    <Toaster />
                </ThemeProvider>
            </body>
        </html>
    );
}
